### PR TITLE
remove extra allocations (Buffer.concat usage)

### PR DESCRIPTION
**Pull request by dcousens**
@fanatid not the cleanest,  but,  it removes all the extra allocations :)

### CODE REVIEW

**Comment by dcousens** [comment]
This is now 1:1 with `decode`,  however,  were you wanting to support `encode` `000001` giving back `01`?

**Comment by fanatid** [comment]
I see what you wanted, but yes, I wanted that `encode` give `01` for `000001`

**Comment by fanatid** [comment]
because this I used `for-loop`

**Comment by dcousens** [comment]
@fanatid but we don't do that for `decode`.
So it would be inconsistent.

Also, you didn't add a test for that :smiley:

**Comment by fanatid** [comment]
sorry, my fault with tests... (I only removed and fixed existed)
initially I wanted add leading zeros for expanding to 32-bytes in `decode`, but bip66 not checked that r/s longer than 32 bytes...

**Comment by fanatid** [comment]
after `decode` we can't come back to `000001` from `01` because we don't knew how much zeros we should put

**Comment by dcousens** [comment]
@fanatid in short, you wanted `encode` to trim all unnecessary padding?  IMHO that is definitely out of scope,  this change brings it back to a simple/sane implementation.
Especially since extraneous leading zeros are BIP66 compliant.

You could easily modify your buffer pre-`encode` to be trimmed with a 1-liner.
Eg count zeros then slice.

**Comment by fanatid** [comment]
but should developer which uses `bitcoinjs/bip66` think about padding? I'd like pass just buffer and don't think about leading zeros..
it is hard draw a line what should do `encode`/`decode` unlike `check`

**Comment by dcousens** [comment]
@fanatid true,  but developers that use this won't be feeding it signatures that have extraneous zeros unless they are making those themselves, in which case,  I'd expect them to know what they're doing.

The change would also block a developer from being able to use `bip66` to encode a extraneously padded signature... even if that seems pointless.

**Comment by fanatid** [comment]
agreed, thanks

**Pull request merged**
